# Generated by Django 6.0.4 on 2026-05-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
