# Generated by Django 6.0.4 on 2026-05-04 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_alter_aluno_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_dificuldade', models.IntegerField(blank=True, null=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, db_column='aluno_id_aluno', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id_log_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(blank=True, max_length=150, null=True)),
                ('tabela_afetada', models.CharField(blank=True, max_length=150, null=True)),
                ('id_registro_afetado', models.IntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, db_column='aluno_id_aluno', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_atividade', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Log de atividade',
                'verbose_name_plural': 'Logs de atividade',
                'db_table': 'log_atividade',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id_relatorio', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(blank=True, max_length=50, null=True)),
                ('total_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, db_column='aluno_id_aluno', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'db_table': 'relatorio',
            },
        ),
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id_sessao_estudo', models.AutoField(primary_key=True, serialize=False)),
                ('tempo_estudo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_sessao', models.DateField(blank=True, null=True)),
                ('nivel_dificuldade', models.IntegerField(blank=True, null=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, db_column='aluno_id_aluno', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_estudo', to='alunos.aluno')),
                ('disciplina', models.ForeignKey(blank=True, db_column='disciplina_id_disciplina', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_estudo', to='sistema_estudos.disciplina')),
            ],
            options={
                'verbose_name': 'Sessão de estudo',
                'verbose_name_plural': 'Sessões de estudo',
                'db_table': 'sessao_estudo',
            },
        ),
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id_sugestao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, db_column='aluno_id_aluno', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sugestoes', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Sugestão',
                'verbose_name_plural': 'Sugestões',
                'db_table': 'sugestao',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('status_tarefa', models.CharField(blank=True, max_length=20, null=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(blank=True, db_column='disciplina_id_disciplina', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='sistema_estudos.disciplina')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'db_table': 'tarefa',
            },
        ),
    ]
