# Generated by Django 6.0.5 on 2026-07-15 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alter_aluno_senha'),
        ('sistema_estudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoPlanejada',
            fields=[
                ('id_sessao_planejada', models.AutoField(primary_key=True, serialize=False)),
                ('data_planejada', models.DateField(blank=True, null=True)),
                ('duracao_prevista_minutos', models.IntegerField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, db_column='aluno_id_aluno', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_planejadas', to='alunos.aluno')),
                ('disciplina', models.ForeignKey(blank=True, db_column='disciplina_id_disciplina', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_planejadas', to='sistema_estudos.disciplina')),
            ],
            options={
                'verbose_name': 'Sessão planejada',
                'verbose_name_plural': 'Sessões planejadas',
                'db_table': 'sessao_planejada',
            },
        ),
    ]
