# Generated by Django 6.0.5 on 2026-08-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0002_alter_aluno_senha'),
        ('sistema_estudos', '0002_sessaoplanejada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caderno',
            fields=[
                ('id_caderno', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(blank=True, default='', max_length=500)),
                ('cor', models.CharField(blank=True, default='#6366f1', max_length=20)),
                ('icone', models.CharField(blank=True, default='book', max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(db_column='aluno_id_aluno', on_delete=django.db.models.deletion.PROTECT, related_name='cadernos', to='alunos.aluno')),
                ('disciplina', models.ForeignKey(blank=True, db_column='disciplina_id_disciplina', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadernos', to='sistema_estudos.disciplina')),
            ],
            options={
                'verbose_name': 'Caderno',
                'verbose_name_plural': 'Cadernos',
                'db_table': 'caderno',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PaginaCaderno',
            fields=[
                ('id_pagina', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.JSONField(default=dict)),
                ('ordem', models.IntegerField(default=0)),
                ('favorita', models.BooleanField(default=False)),
                ('quantidade_palavras', models.IntegerField(default=0)),
                ('quantidade_caracteres', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('caderno', models.ForeignKey(db_column='caderno_id_caderno', on_delete=django.db.models.deletion.PROTECT, related_name='paginas', to='cadernos.caderno')),
            ],
            options={
                'verbose_name': 'Página do caderno',
                'verbose_name_plural': 'Páginas do caderno',
                'db_table': 'pagina_caderno',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ImagemCaderno',
            fields=[
                ('id_imagem', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='uploads/cadernos/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('data_exclusao', models.DateTimeField(blank=True, null=True)),
                ('pagina', models.ForeignKey(db_column='pagina_id_pagina', on_delete=django.db.models.deletion.PROTECT, related_name='imagens', to='cadernos.paginacaderno')),
            ],
            options={
                'verbose_name': 'Imagem do caderno',
                'verbose_name_plural': 'Imagens do caderno',
                'db_table': 'imagem_caderno',
            },
        ),
    ]
